#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/app/src/main/AndroidManifest.xml"
MAIN="$ROOT/app/src/main/java/com/escudo/app/MainActivity.kt"
POLICY="$ROOT/app/src/main/java/com/escudo/app/policy/PolicyController.kt"
SERVICE="$ROOT/app/src/main/java/com/escudo/app/service/VaultGuardService.kt"
EXPIRY="$ROOT/app/src/main/java/com/escudo/app/service/SessionExpiryReceiver.kt"
KEYSTORE="$ROOT/app/src/main/java/com/escudo/app/security/DeviceBoundMac.kt"
BIOMETRIC_KEY="$ROOT/app/src/main/java/com/escudo/app/security/BiometricEnrollmentKey.kt"
BIOMETRIC_GATE="$ROOT/app/src/main/java/com/escudo/app/security/BiometricGate.kt"
PIN_STORE="$ROOT/app/src/main/java/com/escudo/app/security/PinStore.kt"

PROVISION="$ROOT/app/src/main/java/com/escudo/app/policy/ProvisioningController.kt"
PROVISION_MODE="$ROOT/app/src/main/java/com/escudo/app/policy/ProvisioningModeActivity.kt"
CLONE_INSTALLER="$ROOT/app/src/main/java/com/escudo/app/clone/ApkBundleInstaller.kt"
CLONE_SOURCE="$ROOT/app/src/main/java/com/escudo/app/clone/CloneSourceActivity.kt"
REMOVE_PERSONAL="$ROOT/app/src/main/java/com/escudo/app/clone/RemovePersonalCopyActivity.kt"
PERSONAL_AUDIT="$ROOT/app/src/main/java/com/escudo/app/clone/PersonalCopyAuditActivity.kt"
BRIDGE_SERVICE="$ROOT/app/src/main/java/com/escudo/app/clone/CloneBridgeService.kt"
BRIDGE_SECRET="$ROOT/app/src/main/java/com/escudo/app/clone/BridgeSecretStore.kt"
AIDL="$ROOT/app/src/main/aidl/com/escudo/app/clone/ICloneBridge.aidl"

fail() { echo "SECURITY CHECK FAILED: $*" >&2; exit 1; }

! grep -q 'android.permission.INTERNET' "$MANIFEST" || fail "Escudo no debe pedir INTERNET en el MVP"
! grep -q 'android.permission.POST_NOTIFICATIONS' "$MANIFEST" || fail "el onboarding no debe pedir notificaciones para poder iniciar el FGS"
grep -q 'android.permission.HIDE_OVERLAY_WINDOWS' "$MANIFEST" || fail "falta HIDE_OVERLAY_WINDOWS"
grep -q 'android.permission.REQUEST_INSTALL_PACKAGES' "$MANIFEST" || fail "la clonación necesita solicitar instalación de APKs"
grep -q 'android.permission.REQUEST_DELETE_PACKAGES' "$MANIFEST" || fail "la limpieza de la copia personal necesita solicitar desinstalación"
! grep -q 'com.escudo.app.permission.CLONE_SOURCE' "$MANIFEST" || fail "el puente no debe depender de un permiso de firma a través del system forwarder"
grep -q 'FLAG_SECURE' "$MAIN" || fail "falta FLAG_SECURE"
grep -q 'setHideOverlayWindows(true)' "$MAIN" || fail "falta bloqueo de overlays"
grep -q 'setPackagesSuspended' "$POLICY" || fail "falta suspensión real"
grep -q 'setApplicationHidden' "$POLICY" || fail "falta ocultamiento real"
grep -q 'setUninstallBlocked' "$POLICY" || fail "falta bloqueo de desinstalación"
grep -q 'isUninstallBlocked' "$POLICY" || fail "Escudo debe verificar el bloqueo de desinstalación"
grep -q 'setUserControlDisabledPackages' "$POLICY" || fail "falta anti force-stop / clear-data para Escudo"
grep -q 'armAndStart' "$SERVICE" || fail "la sesión debe armarse antes del handoff a la app protegida"
grep -q 'SessionExpiryScheduler.schedule' "$SERVICE" || fail "falta fail-safe de expiración fuera del proceso"
grep -q 'setAndAllowWhileIdle' "$ROOT/app/src/main/java/com/escudo/app/service/SessionExpiryScheduler.kt" || fail "el fail-safe debe sobrevivir Doze sin permiso de alarma exacta"
grep -q 'PolicyController(context).protect' "$EXPIRY" || fail "el receptor de expiración debe volver a proteger la app"
grep -q 'AndroidKeyStore' "$KEYSTORE" || fail "el verificador de PIN debe estar ligado a Android Keystore"
grep -q 'setInvalidatedByBiometricEnrollment(true)' "$BIOMETRIC_KEY" || fail "la biometría debe invalidarse cuando cambia el conjunto de huellas"
grep -q 'AUTH_BIOMETRIC_STRONG' "$BIOMETRIC_KEY" || fail "la clave biométrica debe exigir BIOMETRIC_STRONG"
grep -q 'BiometricPrompt.CryptoObject' "$BIOMETRIC_GATE" || fail "la huella debe autorizar una operación criptográfica real"
! grep -q 'DEVICE_CREDENTIAL' "$BIOMETRIC_GATE" || fail "Escudo no debe aceptar el PIN del teléfono como fallback biométrico"
grep -q 'resetForCurrentEnrollment(appContext)' "$PIN_STORE" || fail "sólo el PIN propio de Escudo debe poder confiar un nuevo conjunto biométrico"
grep -q 'ACTION_PROVISION_MANAGED_PROFILE' "$PROVISION" || fail "falta ruta de provisioning para teléfono personal"
grep -q 'isProvisioningAllowed' "$PROVISION" || fail "Escudo debe verificar que Android permita crear el perfil"
grep -q 'PROVISIONING_MODE_MANAGED_PROFILE' "$PROVISION_MODE" || fail "el provisioning moderno debe elegir Managed Profile"
grep -q 'android.permission.BIND_DEVICE_ADMIN' "$MANIFEST" || fail "las activities de provisioning deben quedar limitadas al sistema"
grep -q 'PackageInstaller.SessionParams' "$CLONE_INSTALLER" || fail "falta instalador base+splits dentro del perfil"
grep -q 'setAppPackageName' "$CLONE_INSTALLER" || fail "el instalador debe fijar el package esperado"
grep -q 'EXTRA_BRIDGE_BINDER' "$CLONE_SOURCE" || fail "la Activity cross-profile debe devolver un Binder, no file descriptors"
grep -q 'ParcelFileDescriptor.MODE_READ_ONLY' "$BRIDGE_SERVICE" || fail "los APKs fuente deben abrirse sólo lectura desde el Binder"
grep -q 'getPackagesForUid(Binder.getCallingUid())' "$BRIDGE_SERVICE" || fail "el Binder debe verificar que cada IPC provenga del paquete Escudo"
grep -q 'EXTRA_PROVISIONING_ADMIN_EXTRAS_BUNDLE' "$PROVISION" || fail "el secreto de emparejamiento debe viajar por provisioning oficial"
grep -q 'MessageDigest.isEqual' "$BRIDGE_SECRET" || fail "la comparación del secreto debe ser de tiempo constante"
grep -q 'ParcelFileDescriptor\[\]' "$AIDL" || fail "los APKs deben viajar por AIDL/ParcelFileDescriptor"
grep -q 'PROFILE_PROVISIONING_COMPLETE' "$MANIFEST" || fail "falta callback de finalización del perfil"
grep -q 'ACTION_UNINSTALL_PACKAGE' "$REMOVE_PERSONAL" || fail "la copia personal debe limpiarse mediante UI oficial de Android"
grep -q 'ACTION_AUDIT_PERSONAL_COPIES' "$PERSONAL_AUDIT" || fail "falta auditoría silenciosa de copias exteriores"
grep -q 'BridgeSecretStore(this).matches' "$PERSONAL_AUDIT" || fail "la auditoría exterior debe autenticar el perfil solicitante"
grep -q 'crossProfilePersonalCopyAuditIntent' "$PROVISION" || fail "falta puente de auditoría al perfil personal"
grep -q 'personalAuditHealthy' "$MAIN" || fail "la UI no puede declarar protección fuerte sin auditoría exterior"
grep -q 'OPEN_SECURE_ESCUDO' "$MANIFEST" || fail "falta entrada única hacia el perfil seguro"
grep -q 'activity-alias' "$MANIFEST" || fail "el launcher debe ser un alias controlable por perfil"
grep -q 'FLAG_PARENT_CAN_ACCESS_MANAGED' "$PROVISION" || fail "el único icono personal debe poder abrir la bóveda administrada"
grep -q 'EscudoLauncher' "$PROVISION" || fail "el launcher duplicado del perfil administrado debe deshabilitarse"
grep -q 'addCrossProfileIntentFilter' "$PROVISION" || fail "falta puente cross-profile oficial"

echo "Escudo security regression check: PASS"
